# - name: Install Postgres 
#   # Needs separate Play: https://github.com/ansible/ansible/issues/2107)
#   hosts: idp
#   roles:
#     - db

#   handlers:
#     - name: restart postgres
#       service: name=postgresql state=restarted


- name: Install Shibboleth IdP v3 for UbuntuNet Alliance
  hosts: idp
  become: True  
  roles:
    - webserver
    - db
    - appserver
    - idp
 
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    - name: restart tomcat
      service: name=tomcat{{ tomcat_version }} state=restarted

    - name: restart postgres
      service: name=postgresql state=restarted

