
# 6.12. Hibernate ORM workaround for JPAStorageService

- name: Create META-INF directory
  file: >
    path=/opt/shibboleth-idp/edit-webapp/WEB-INF/classes/META-INF
    state=directory

- name: Copy ORM workaround
  copy: > 
    src=files/orm.xml 
    dest=/opt/shibboleth-idp/edit-webapp/WEB-INF/classes/META-INF

- name: Rebuild id.war
  shell: "JAVACMD=/usr/bin/java /opt/shibboleth-idp/bin/build.sh -Didp.target.dir=/opt/shibboleth-idp"
  notify: restart tomcat


# 6.13. Web application enablement

- name: Enable IdP Web application
  template: > 
    src=catalina_idp.xml.j2 
    dest=/etc/tomcat7/Catalina/localhost/idp.xml
  notify: restart tomcat
